server:
  port: 8080

spring:
  datasource:
    username: root
    password: Duyngan96
    url: jdbc:mysql://localhost:3307/film
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true

